spring:
  application:
    name: caixasugestoes
  datasource:
    url: jdbc:h2:mem:fatec-db;DB_CLOSE_ON_EXIT=false
    username: aluno
    password: 123edc
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        formatSql: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 9000

springdoc:
  swagger-ui.path: /openapi/swagger-ui.html 
  api-docs.path: /openapi/v3/api-docs
  packagesToScan: dev.sdras.caixasugestoes.resources
  pathsToMatch: /**

api:
  common:
    version: 1.0.0
    title: API de Caixa de Sugestões - Fatec Araras
    description: API para gerenciamento de sugestões desenvolvidas pelos alunos da Fatec Araras
    termsOfService: Em desenvolvimento
    license: Em desenvolvimento
    licenseUrl: Em desenvolvimento
    externalDocDesc: Em desenvolvimento
    externalDocUrl: Em desenvolvimento
    contact:
      name: Esdras B Silva
      url: github.com/f290DSM
      email: esdras.silva9@fatec.sp.gov.br